language: julia

os:
  - linux

julia:
  - 1.5

addons:
    apt: # apt-get for linux
        packages:
          - git
          - gfortran
          - libnetcdf-dev
          - libnetcdff-dev
          - libopenmpi-dev
          - make
          - netcdf-bin
          - openmpi-bin
          - perl
          - python3-pip
          - python3-setuptools
          - python3-matplotlib
          - subversion
          - wget

notifications:
  email: false


before_install:
    - python3 -m pip install motuclient

script:
    - julia --project --color=yes --check-bounds=yes -e 'using Pkg; Pkg.instantiate(); Pkg.build(); Pkg.test(; coverage=true)'

# using default test script
after_success:
  # push coverage results to Coveralls
  - julia -e 'using Pkg; cd(Pkg.dir("DIVAnd")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'using Pkg; cd(Pkg.dir("DIVAnd")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'


jobs:
  include:
    - stage: "Documentation"
      julia: 1.5
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.instantiate();
                                    Pkg.develop(PackageSpec(path=pwd()))'
        - julia --project=docs/ docs/make.jl
      after_success: skip
